canonical: "https://afriscic.github.io/EAHP_Interoperabillty/"
fhirVersion: 5.0.0
FSHOnly: false
applyExtensionMetadataToRoot: false
id: eahp-interoperability-ig
name: EAHPInteroperabilityIG
status: draft
version: "0.0.1"
packageId: "org.eahp.interoperability"
copyrightYear: 2025
releaseLabel: "0.0.1"
dependencies: 
  hl7.fhir.r5.core: 5.0.0
menu:
  Index: index.html
  Artifacts: artifacts.html
  Table of Contents: toc.html
